/**
 * ═══════════════════════════════════════════════════════════════════
 * utils/ai/locator/locatorSuggester.js — AI Locator Suggestion Engine
 *
 * Given a URL (live) or accessibility snapshot (offline), generates
 * ranked locator suggestions for all interactable elements.
 *
 * Outputs:
 *  - console: table of discovered elements
 *  - JSON:    locator-suggestions.json
 *  - JS:      suggested-locators.js (ready-to-paste POM code)
 *
 * Usage:
 *   node utils/ai/locator/locatorSuggester.js --url https://app.example.com/login
 *   node utils/ai/locator/locatorSuggester.js --snapshot ./aria-snapshot.json
 * ═══════════════════════════════════════════════════════════════════
 */
import { chromium } from 'playwright';
import fs from 'fs/promises';
import path from 'path';
import { parseArgs } from 'util';

import { parseDomSnapshot, extractTestIds } from './domParser.js';
import { frameworkConfig } from '../../../config/framework.config.js';

// ════════════════════════════════════════════════════════════════════
// CLI Args
// ════════════════════════════════════════════════════════════════════
const { values: args } = parseArgs({
  args: process.argv.slice(2),
  options: {
    url:      { type: 'string', short: 'u' },
    snapshot: { type: 'string', short: 's' },
    output:   { type: 'string', short: 'o', default: './reports/locator-suggestions' },
    pageName: { type: 'string', short: 'n', default: 'DiscoveredPage' },
  },
  strict: false,
});

// ════════════════════════════════════════════════════════════════════
// Locator Confidence Scorer
// ════════════════════════════════════════════════════════════════════

const LOCATOR_SCORES = {
  getByRole:    100,   // WAI-ARIA compliance, most resilient
  getByTestId:  90,    // Explicit test IDs, very stable
  getByLabel:   80,    // Semantic form labels
  getByText:    60,    // Brittle if text changes, but human-readable
  getByPlaceholder: 50,
  css:          20,    // Fragile — flagged with warning
  unknown:      0,
};

/**
 * Enriches elements with confidence scores and stability ratings.
 * @param {import('./domParser.js').ParsedElement[]} elements
 * @returns {Array}
 */
function scoreLocators(elements) {
  return elements.map((el) => {
    const confidence = LOCATOR_SCORES[el.locatorType] ?? 0;
    const stability = confidence >= 80 ? 'HIGH' : confidence >= 50 ? 'MEDIUM' : 'LOW';
    const warning = el.locatorType === 'css'
      ? '⚠️  CSS locator — fragile, consider adding data-testid'
      : null;

    return {
      ...el,
      confidence,
      stability,
      warning,
    };
  });
}

// ════════════════════════════════════════════════════════════════════
// POM Code Generator
// ════════════════════════════════════════════════════════════════════

/**
 * Generates a ready-to-use Page Object Model JavaScript snippet.
 * @param {Array} elements
 * @param {string} pageName
 * @returns {string}
 */
function generatePomCode(elements, pageName) {
  const interactable = elements.filter((el) => el.isInteractable && el.confidence > 0);

  const locatorLines = interactable
    .map((el) => {
      const propName = _toCamelCase(el.name || el.role);
      const comment  = el.confidence < 80 ? ` // ${el.stability} confidence — consider adding data-testid` : '';
      return `    this.${propName} = ${el.suggestedLocator};${comment}`;
    })
    .join('\n');

  return `/**
 * AUTO-GENERATED by SmartGen Locator Engine
 * Page: ${pageName}
 * Generated: ${new Date().toISOString()}
 *
 * Locator Strategy Summary:
${elements
  .reduce((acc, el) => {
    acc[el.locatorType] = (acc[el.locatorType] || 0) + 1;
    return acc;
  }, {})
  |> (counts) => Object.entries(counts)
      .map(([type, count]) => ` *   ${type}: ${count} element(s)`)
      .join('\n')}
 */
import { BasePage } from '../../pages/BasePage.js';

export class ${pageName} extends BasePage {
  /**
   * @param {import('playwright').Page} page
   */
  constructor(page) {
    super(page);

${locatorLines}
  }
}
`;
}

// ════════════════════════════════════════════════════════════════════
// Main
// ════════════════════════════════════════════════════════════════════

async function run() {
  console.log('\n🔍 Locator Suggestion Engine Starting...\n');

  let elements = [];
  let pageTitle = args.pageName;

  if (args.url) {
    // ── Live URL mode ──────────────────────────────────────────
    console.log(`🌐 Navigating to: ${args.url}`);
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext();
    const page    = await context.newPage();

    await page.goto(args.url, { waitUntil: 'networkidle' });
    pageTitle = await page.title() || args.pageName;

    console.log(`📄 Page title: "${pageTitle}"`);
    console.log('🔬 Parsing accessibility tree...');

    elements = await parseDomSnapshot(page);
    const testIds = await extractTestIds(page);

    // Merge testIds into elements
    const testIdByLabel = new Map(testIds.map((t) => [t.ariaLabel || t.text, t.testId]));
    elements = elements.map((el) => {
      const tid = testIdByLabel.get(el.name);
      if (tid && !el.testId) {
        return { ...el, testId: tid };
      }
      return el;
    });

    await browser.close();

  } else if (args.snapshot) {
    // ── Static snapshot mode ───────────────────────────────────
    console.log(`📂 Reading snapshot: ${args.snapshot}`);
    const { parseStaticSnapshot } = await import('./domParser.js');
    const raw = await fs.readFile(args.snapshot, 'utf-8');
    elements = parseStaticSnapshot(JSON.parse(raw));
  } else {
    console.error('❌ Provide --url <URL> or --snapshot <file.json>');
    process.exit(1);
  }

  // ── Score and rank ─────────────────────────────────────────────
  const scored = scoreLocators(elements).sort((a, b) => b.confidence - a.confidence);

  console.log(`\n✅ Discovered ${scored.length} elements (${scored.filter((e) => e.isInteractable).length} interactable)\n`);

  // ── Print table ────────────────────────────────────────────────
  console.log('┌─────────────────────────────────────────────────────────────────┐');
  console.log('│  Role              │ Name                  │ Type       │ Score │');
  console.log('├─────────────────────────────────────────────────────────────────┤');
  for (const el of scored.slice(0, 20)) {
    const role = el.role.padEnd(18);
    const name = (el.name || '').substring(0, 21).padEnd(21);
    const type = el.locatorType.padEnd(10);
    const score = String(el.confidence).padEnd(5);
    console.log(`│  ${role} │ ${name} │ ${type} │ ${score} │`);
  }
  console.log('└─────────────────────────────────────────────────────────────────┘\n');

  // ── Write outputs ───────────────────────────────────────────────
  await fs.mkdir(args.output, { recursive: true });

  const jsonPath = path.join(args.output, 'locator-suggestions.json');
  const jsPath   = path.join(args.output, 'suggested-locators.js');

  await fs.writeFile(jsonPath, JSON.stringify(scored, null, 2), 'utf-8');

  // Generate POM code (simple version without pipeline operator)
  const counts = scored.reduce((acc, el) => {
    acc[el.locatorType] = (acc[el.locatorType] || 0) + 1;
    return acc;
  }, {});
  const countLines = Object.entries(counts)
    .map(([type, count]) => ` *   ${type}: ${count} element(s)`)
    .join('\n');

  const interactable = scored.filter((el) => el.isInteractable && el.confidence > 0);
  const locatorLines = interactable
    .map((el) => {
      const propName = _toCamelCase(el.name || el.role);
      const comment  = el.confidence < 80 ? ` // ${el.stability} confidence` : '';
      return `    this.${propName} = ${el.suggestedLocator};${comment}`;
    })
    .join('\n');

  const pomCode = `/**
 * AUTO-GENERATED by SmartGen Locator Engine
 * Page: ${pageTitle}
 * Generated: ${new Date().toISOString()}
 *
 * Locator Strategy Distribution:
${countLines}
 */
import { BasePage } from '../../pages/BasePage.js';

export class ${_toPascalCase(pageTitle)}Page extends BasePage {
  constructor(page) {
    super(page);

${locatorLines}
  }
}
`;

  await fs.writeFile(jsPath, pomCode, 'utf-8');

  console.log(`📄 JSON suggestions → ${jsonPath}`);
  console.log(`📝 POM code snippet → ${jsPath}`);

  // ── Stability summary ──────────────────────────────────────────
  const high   = scored.filter((e) => e.stability === 'HIGH').length;
  const medium = scored.filter((e) => e.stability === 'MEDIUM').length;
  const low    = scored.filter((e) => e.stability === 'LOW').length;

  console.log(`\n📊 Stability Summary:`);
  console.log(`   HIGH   (≥80): ${high} elements`);
  console.log(`   MEDIUM (≥50): ${medium} elements`);
  console.log(`   LOW    (<50): ${low} elements`);

  if (low > 0) {
    console.warn(`\n⚠️  ${low} element(s) have LOW stability locators.`);
    console.warn('   Add data-testid attributes to these elements for better test resilience.');
  }
}

// ════════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════════

function _toCamelCase(str) {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .map((word, i) => (i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()))
    .join('');
}

function _toPascalCase(str) {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

run().catch((err) => {
  console.error('❌ Locator Suggester failed:', err);
  process.exit(1);
});
